<h1>Arrays</h1>

In [1]:
#importando a Biblioteca Numpay
import numpy as np

In [2]:
array = np.array(["C#", "Python", "Java", "R", "Ruby"])

In [3]:
type(array)

numpy.ndarray

In [4]:
array

array(['C#', 'Python', 'Java', 'R', 'Ruby'], dtype='<U6')

In [5]:
array_2 = np.array([['Café', 'Arroz', 'Feijão'], [2.50, 7.99, 5.40]])

In [6]:
array_2

array([['Café', 'Arroz', 'Feijão'],
       ['2.5', '7.99', '5.4']], dtype='<U6')

In [7]:
a = np.array([[20, 30, 40], [10, 15, 40]])
a

array([[20, 30, 40],
       [10, 15, 40]])

In [8]:
a.shape

(2, 3)

In [9]:
b = np.array([[2,4,6], [3,5,7],[8,9,0]])
b

array([[2, 4, 6],
       [3, 5, 7],
       [8, 9, 0]])

In [10]:
b.shape

(3, 3)

In [11]:
#dimensão
b.ndim

2

In [12]:
a.ndim

2

In [13]:
b.diagonal()

array([2, 5, 0])

In [14]:
b.max()

9

In [15]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
array = np.arange(0, 110, 10)
array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
array = np.linspace(0, 10, 20)
array

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

<h1>Estrutura de Matriz</h1>

In [18]:
matriz = np.zeros((10, 10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
matriz = np.ones((5, 5))
matriz

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
matriz = np.eye((5))
matriz

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#Escolhendo os valores da diagonal
matriz = np.diag((2,3,4))
matriz

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [22]:
#criando uma matriz vazia
matriz_vazia = np.empty((3,2))
matriz_vazia

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
matriz_a = np.array([[1,4,5], [2,3,4], [2,5,6]])
matriz_a

array([[1, 4, 5],
       [2, 3, 4],
       [2, 5, 6]])

In [24]:
matriz_b = np.array([[5,4,7], [0,3,6], [2,5,6]])
matriz_b

array([[5, 4, 7],
       [0, 3, 6],
       [2, 5, 6]])

In [25]:
matriz_soma = matriz_a + matriz_b
matriz_soma

array([[ 6,  8, 12],
       [ 2,  6, 10],
       [ 4, 10, 12]])

In [26]:
matriz_subtracao = matriz_a - matriz_b
matriz_subtracao

array([[-4,  0, -2],
       [ 2,  0, -2],
       [ 0,  0,  0]])

In [27]:
matriz_mult = matriz_a * matriz_b
matriz_mult

array([[ 5, 16, 35],
       [ 0,  9, 24],
       [ 4, 25, 36]])

<h1>numpy.tile</h1>

In [28]:
np.tile(np.array([[2,3,4], [5,8,7], [1,3,0]]), 2)

array([[2, 3, 4, 2, 3, 4],
       [5, 8, 7, 5, 8, 7],
       [1, 3, 0, 1, 3, 0]])

In [29]:
np.tile(np.array([[2,3,4], [5,8,7], [1,3,0]]), (10,120))

array([[2, 3, 4, ..., 2, 3, 4],
       [5, 8, 7, ..., 5, 8, 7],
       [1, 3, 0, ..., 1, 3, 0],
       ...,
       [2, 3, 4, ..., 2, 3, 4],
       [5, 8, 7, ..., 5, 8, 7],
       [1, 3, 0, ..., 1, 3, 0]])

<h1>Tipagem de dado</h1>

In [30]:
a = np.array([10, 30, 20], dtype='float')
a

array([10., 30., 20.])

In [31]:
type(a)

numpy.ndarray

In [32]:
a.shape

(3,)

In [33]:
a.dtype

dtype('float64')

In [34]:
b = np.array([10, 30, 20])
b

array([10, 30, 20])

In [35]:
b.dtype

dtype('int32')

In [36]:
c = np.array([10, 30, 20, 4.6])
c

array([10. , 30. , 20. ,  4.6])

In [37]:
c.dtype

dtype('float64')

In [38]:
d = np.array(['Linguagem', 'Programação', 'Python'])
d

array(['Linguagem', 'Programação', 'Python'], dtype='<U11')

In [39]:
d.dtype

dtype('<U11')

In [40]:
e = np.array([True, False, True, False])
e

array([ True, False,  True, False])

In [41]:
e.dtype

dtype('bool')

<h1>Cast de Arrays</h1>

In [42]:
f = np.array([10, 30, 20, 4.6])
f.dtype

dtype('float64')

In [43]:
f.astype(int)

array([10, 30, 20,  4])

<h1>Criando Arrays com operações aritiméticas em tempo de execução</h1>

In [44]:
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [45]:
array = np.arange(0,10) * 10
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
array = np.arange(10) ** 2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

<h1>Operações Aritiméticas entre Arrays</h1>

In [47]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [48]:
b = np.arange(0, 6) + 1
b

array([1, 2, 3, 4, 5, 6])

In [49]:
c = np.arange(0, 6) - 1
c

array([-1,  0,  1,  2,  3,  4])

In [50]:
d = np.arange(0, 6) * 2
d

array([ 0,  2,  4,  6,  8, 10])

In [51]:
e = np.arange(0, 6) / 2
e

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [52]:
f = np.arange(0, 6) % 2
f

array([0, 1, 0, 1, 0, 1], dtype=int32)

In [53]:
g = np.arange(0, 6) // 2
g

array([0, 0, 1, 1, 2, 2], dtype=int32)

In [54]:
print('array_a',a,'\narray_b',b)
print('Result:',a+b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [ 1  3  5  7  9 11]


In [55]:
print('array_a',a,'\narray_b',b)
print('Result:',a-b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [-1 -1 -1 -1 -1 -1]


In [56]:
print('array_a',a,'\narray_b',b)
print('Result:',a*b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [ 0  2  6 12 20 30]


In [57]:
print('array_a',a,'\narray_b',b)
print('Result:',a/b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [0.         0.5        0.66666667 0.75       0.8        0.83333333]


In [58]:
print('array_a',a,'\narray_b',b)
print('Result:',a//b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [0 0 0 0 0 0]


In [59]:
print('array_a',a,'\narray_b',b)
print('Result:',a%b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [0 1 2 3 4 5]


In [60]:
print('array_a',a,'\narray_b',b)
print('Result:',a**b)

array_a [0 1 2 3 4 5] 
array_b [1 2 3 4 5 6]
Result: [    0     1     8    81  1024 15625]


<h1>Comparação de Arrays</h1>

In [61]:
a == b

array([False, False, False, False, False, False])

In [62]:
a > b

array([False, False, False, False, False, False])

In [63]:
a < b

array([ True,  True,  True,  True,  True,  True])

In [64]:
array1 = np.array([True, False, True, True])
array2 = np.array([False, False, False, True])

In [65]:
np.logical_and(array1, array2)

array([False, False, False,  True])

In [66]:
np.logical_or(array1, array2)

array([ True, False,  True,  True])

In [67]:
np.logical_xor(array1, array2)

array([ True, False,  True, False])

In [68]:
np.logical_not(array1)

array([False,  True, False, False])

In [69]:
a = np.array([3, 4, 5])
b = np.array([2, 4, 3])

In [70]:
#hadmart Product
a * b

array([ 6, 16, 15])

In [71]:
#dot Product
np.dot(a,b)

37

<h1>Cópia de Arrays</h1>

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
b = a[5:]
b

array([5, 6, 7, 8, 9])

In [89]:
a[:]=0
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
b

array([0, 0, 0, 0, 0])

In [91]:
c = np.arange(0,5)
c

array([0, 1, 2, 3, 4])

In [92]:
d = np.copy(c)
d

array([0, 1, 2, 3, 4])

In [93]:
c[:] = 0
c

array([0, 0, 0, 0, 0])

In [94]:
d

array([0, 1, 2, 3, 4])

<h1>Testando o Tempo Python</h1>

In [1]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [2]:
def soma(a,b):
    x = a
    y = b
    resultado = a + b
    return resultado

In [3]:
%timeit soma(2,5)

163 ns ± 3.42 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [4]:
def soma(a,b):
    resultado = a + b
    return resultado

In [5]:
%timeit soma(2,5)

143 ns ± 1.46 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [4]:
def soma(a,b):
    return a + b

In [6]:
%timeit soma(2,5)

135 ns ± 2.44 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


<h1>Testando Arrays Perfomático</h1>

In [1]:
%%timeit
a = []

for i in range(100):
    a.append(i +7)

11.2 µs ± 369 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%%timeit
a = [7 + i for i in range(100)]


6.84 µs ± 988 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [1]:
import numpy as np

In [6]:
%%timeit
a = [7 + np.arange(100)] 

2 µs ± 94.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<h1>Array Unidimensional</h1>

In [2]:
a = [2, 3, 4, 5, 6, 7]

array = np.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [5]:
#verificando o tamanho do array
print(array.shape)

(6,)


In [6]:
#fatinando o array pelo índice
array[4]

6

In [7]:
array[3:]

array([5, 6, 7])

In [9]:
#Trazendo o útimo elemento
array[-1]

7

In [10]:
array[1:5]

array([3, 4, 5, 6])

In [24]:
array[-6:-1]

array([2, 3, 4, 5, 6])

In [25]:
array[5:]

array([7])

In [26]:
array[::-1]

array([7, 6, 5, 4, 3, 2])

In [29]:
array[0:6:2]

array([2, 4, 6])

In [30]:
#cópia por referência
b = array[:]
b

array([2, 3, 4, 5, 6, 7])

In [34]:
#concartenando dois arrays
x = np.array([2,3,8,9])
y = np.array([6,0,1,7])
z = np.concatenate([x, y])
z

array([2, 3, 8, 9, 6, 0, 1, 7])

<h1>Array Multidimensionais</h1>

In [35]:
a = np.array([[1,2,3], [4,5,6], [0,3,9], [1,0,7]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 3, 9],
       [1, 0, 7]])

In [36]:
#Trazendo a primeira linha
a[0]

array([1, 2, 3])

In [42]:
#Trazendo a ultima linha
a[3:,:]

array([[1, 0, 7]])

In [44]:
#primeira linha e última coluna
a[0,-1]

3

In [45]:
#última Coluna
a[:,-1]

array([3, 6, 9, 7])

In [47]:
#segunda Coluna
a[:,-2]

array([2, 5, 3, 0])

In [48]:
#Primeira Coluna
a[:,-3]

array([1, 4, 0, 1])

In [53]:
#Atribuindo um valor a matris => Terceira linha segunda coluna
a[2,-2] = -4
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 0 -4  9]
 [ 1  0  7]]


In [58]:
a[2,1] = -2
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 0 -2  9]
 [ 1  0  7]]


<h1>Trabalhando com Intervalos</h1>

In [67]:
#posições centrais
print(a)
print('*'*13)
print(a[1:3,:])

[[ 1  2  3]
 [ 4  5  6]
 [ 0 -2  9]
 [ 1  0  7]]
*************
[[ 4  5  6]
 [ 0 -2  9]]


In [69]:
#Pegando somente a última coluna
print(a)
print('*'*13)
a[:,-1]

[[ 1  2  3]
 [ 4  5  6]
 [ 0 -2  9]
 [ 1  0  7]]
*************


array([3, 6, 9, 7])

In [73]:
#concartenando arrays Multidimensionais
a = np.array([[5,2,1], [4,9,0]])
b = np.array([[3,2,4]])
c = np.concatenate((a,b))
print(c)

[[5 2 1]
 [4 9 0]
 [3 2 4]]


<h1>Numpy Matrizes</h1>

In [12]:
#Matrizes são objetos estritamente bidimensionais, o que torna mais fácil as operações aritiméticas

a = np.matrix([[1,2], [3,4]])
b = np.matrix([[0,1], [2,9]])

z = np.array([
    [[2,5], [4,6]],
    [[4,3], [7,5]],
    [[0,1], [1,0]]
])

y = np.array([1,2,3,4])

In [14]:
print(type(a))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [15]:
print(type(b))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [16]:
print(type(z))

<class 'numpy.ndarray'>


In [19]:
print(type(y))

<class 'numpy.ndarray'>


In [21]:
print(a)

[[1 2]
 [3 4]]


In [22]:
print(b)

[[0 1]
 [2 9]]


In [23]:
print(a+b)

[[ 1  3]
 [ 5 13]]


In [24]:
print(a-b)

[[ 1  1]
 [ 1 -5]]


In [26]:
print(a)
print("*"*13)
print(b)
print("*"*13)
print(a*b)

[[1 2]
 [3 4]]
*************
[[0 1]
 [2 9]]
*************
[[ 4 19]
 [ 8 39]]


In [27]:
#Mutiplicação índice a índice
print(np.multiply(a, b))

[[ 0  2]
 [ 6 36]]


<h1>Inversa</h1>

In [28]:
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
from numpy.linalg import inv

In [31]:
print(inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


<h1>Transposta</h1>

In [32]:
print(a.T)

[[1 3]
 [2 4]]


<h1>Transporte e Reshaping de vetores e Matrizes</h1>

In [34]:
a = np.array([[1, 45, 11], [12, 45, 7]])
a

array([[ 1, 45, 11],
       [12, 45,  7]])

In [35]:
a.T

array([[ 1, 12],
       [45, 45],
       [11,  7]])

In [36]:
np.transpose(a)

array([[ 1, 12],
       [45, 45],
       [11,  7]])

<h1>Braodcasting</h1>

In [7]:
b = np.array([[100,200,500]])
print(b)

[[100 200 500]]


In [8]:
print(b.T + b)

[[ 200  300  600]
 [ 300  400  700]
 [ 600  700 1000]]


<h1>Transformando Matriz em Array</hq>

In [17]:
c = np.array([np.arange(10, 60, 10), np.arange(100, 150, 10)])
print(c)

[[ 10  20  30  40  50]
 [100 110 120 130 140]]


In [13]:
c.shape

(2, 5)

In [15]:
c.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [18]:
c.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

<h1>Operações Lógicas</h1>

In [20]:
e = np.random.randint(1, 10, size=(4,4))
e

array([[1, 5, 8, 5],
       [3, 1, 3, 7],
       [3, 2, 7, 5],
       [4, 6, 2, 7]])

In [22]:
#Para o retorno ser verdadeiro bata alguma condição ser Verdade lógica do OR
np.any((e % 7) == 0)

True

In [23]:
#Para o retorno ser verdadeiro bata queb toda condição ser Verdade lógica do AND
np.all((e % 7) == 0) 

False

In [25]:
np.all(e < 9) 

True

<h1>Rashaping</h1>

In [34]:
array = np.arange(1,16)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
array = np.arange(1,17)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [37]:
array.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<h1>Ordenando o Array</h1>

In [38]:
array = np.array([[3,2], [10,-1]])
array

array([[ 3,  2],
       [10, -1]])

In [41]:
#Ordenando por linhas
array.sort(axis = 1)
array

array([[ 2,  3],
       [-1, 10]])

In [42]:
array = np.array([[3,2], [10,-1]])
array

array([[ 3,  2],
       [10, -1]])

In [43]:
#Ordenando por Colunas
array.sort(axis = 0)
array

array([[ 3, -1],
       [10,  2]])