<h1><font color='Blue' size=33><b>Biblioteca Numpy</font></b></h1>

In [1]:
import numpy as np

In [2]:
lista = np.array(list(range(1,6)))
lista

array([1, 2, 3, 4, 5])

In [11]:
lista1 = [[1,2,4,5], [2, 3, 4, 5]]
lista2 = np.array(lista1)
lista2

array([[1, 2, 4, 5],
       [2, 3, 4, 5]])

In [12]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [13]:
dados1 = np.arange(1, 6)
dados1

array([1, 2, 3, 4, 5])

In [14]:
dados2 = np.zeros(5)
dados2

array([0., 0., 0., 0., 0.])

In [16]:
dados3 = np.zeros((5,3))
dados3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
dados4 = np.ones(4)
dados4

array([1., 1., 1., 1.])

In [18]:
dados5 = np.ones((4,4))
dados5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
dados6 = np.linspace(4, 3, 50)
dados6

array([4.        , 3.97959184, 3.95918367, 3.93877551, 3.91836735,
       3.89795918, 3.87755102, 3.85714286, 3.83673469, 3.81632653,
       3.79591837, 3.7755102 , 3.75510204, 3.73469388, 3.71428571,
       3.69387755, 3.67346939, 3.65306122, 3.63265306, 3.6122449 ,
       3.59183673, 3.57142857, 3.55102041, 3.53061224, 3.51020408,
       3.48979592, 3.46938776, 3.44897959, 3.42857143, 3.40816327,
       3.3877551 , 3.36734694, 3.34693878, 3.32653061, 3.30612245,
       3.28571429, 3.26530612, 3.24489796, 3.2244898 , 3.20408163,
       3.18367347, 3.16326531, 3.14285714, 3.12244898, 3.10204082,
       3.08163265, 3.06122449, 3.04081633, 3.02040816, 3.        ])

In [21]:
dados7 = np.linspace(2, 3, 10)
dados7

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [22]:
dados8 = np.eye(4)
dados8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Números Aleatórios**

In [24]:
aleatorio1 = np.random.rand(4)
aleatorio1

array([0.3211391 , 0.25017606, 0.10357684, 0.97145052])

In [25]:
aleatorio2 = np.random.rand(3, 2)
aleatorio2

array([[0.14264233, 0.70610884],
       [0.10527313, 0.04815071],
       [0.43456831, 0.64430035]])

In [26]:
aleatorio3 = np.random.randn(4)
aleatorio3

array([-1.69758205, -0.8765517 , -0.33867151, -0.51604458])

In [27]:
aleatorio4 = np.random.randn(4,4)
aleatorio4

array([[-0.88883616,  0.67245595, -0.28715008, -0.02130468],
       [-0.24964805,  0.67690271,  0.22428901,  0.18023043],
       [-1.07751441, -0.3321148 , -0.02361684,  1.6062876 ],
       [-1.08346838,  3.50901065,  0.19302141,  0.49503351]])

**Números Inteiros Aleatórios**

In [32]:
aleatorio5 = np.random.randint(4)
aleatorio5

1

In [33]:
aleatorio6 = np.random.randint(1, 20)
aleatorio6

9

In [34]:
aleatorio7 = np.random.randint(1, 20, 4)
aleatorio7

array([ 4, 13,  6, 19])

**Mudando o Tamanho**

In [36]:
array = np.random.randint(1, 100, 20)
array

array([69, 69, 20, 84, 77, 77, 99, 71,  8, 86, 75, 38, 41, 23, 86,  7, 11,
       73, 13, 49])

In [39]:
matriz = array.reshape(5, 4)
matriz

array([[69, 69, 20, 84],
       [77, 77, 99, 71],
       [ 8, 86, 75, 38],
       [41, 23, 86,  7],
       [11, 73, 13, 49]])

**Valor máximo & valor Mínimo**

In [42]:
array = np.random.randint(1,50, 10)
array

array([11, 30,  6,  5, 31, 18,  9, 39, 31, 48])

In [47]:
valor_maximo = array.max()
valor_maximo

48

In [45]:
valor_minimo = array.min()
valor_minimo

5

In [48]:
#posição do valor máximo
posicao_valor_maximo = array.argmax()
posicao_valor_maximo

9

In [50]:
array[9]

48

In [49]:
#posição do valor mínimo
posicao_valor_minimo = array.argmin()
posicao_valor_minimo

3

In [52]:
array[3]

5

**Array com 1 Dimensão**

In [53]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#indexação
array[7]

8

In [55]:
array[-1]

9

In [56]:
array[2:6]

array([3, 4, 5, 6])

In [57]:
array[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array[:3]

array([1, 2, 3])

In [59]:
array[5:]

array([6, 7, 8, 9])

In [60]:
array2 = array.copy()
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
array2[2] = 50
array2

array([ 1,  2, 50,  4,  5,  6,  7,  8,  9])

In [62]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Array com 2 Dimensão**

In [63]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
array[0]

array([ 1,  2, 10])

In [71]:
array[:2]

array([[ 1,  2, 10],
       [ 4,  5,  6]])

In [72]:
array[-1]

array([7, 8, 9])

In [73]:
array[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [66]:
array[2][1]

8

In [74]:
array[2,1]

8

In [75]:
array[0,2] = 10
array

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [76]:
#selecionar a coluna
array[:,0]

array([1, 4, 7])

In [77]:
array[:,-1]

array([10,  6,  9])

In [78]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [79]:
array[:,1:]

array([[ 2, 10],
       [ 5,  6],
       [ 8,  9]])

**Seleção por Condição**

In [82]:
array = np.arange(1, 14)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [83]:
condicao = array > 5
condicao

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True])

In [84]:
array[condicao]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [86]:
array[array > 5]


array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [90]:
pares = array[ array % 2 == 0]
pares

array([ 2,  4,  6,  8, 10, 12])

In [91]:
impares = array[ array % 2 != 0]
impares

array([ 1,  3,  5,  7,  9, 11, 13])

**Operação com Arrays**

In [92]:
array = np.arange(3, 7)
array

array([3, 4, 5, 6])

In [96]:
resultado = array * 2
resultado

array([ 6,  8, 10, 12])

In [97]:
resultado = array - array 
resultado

array([0, 0, 0, 0])

In [98]:
resultado = array + array 
resultado

array([ 6,  8, 10, 12])